import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/nav/nav";
import { VideoProvider } from "@/context/video";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [ "300", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <VideoProvider>
    <html lang="en">
      <body
        className={` ${poppins.className}antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
    </VideoProvider>
    </ClerkProvider>
  );
}
